version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@11
  oss-docs: fairwinds/oss-docs@dev:sudermanjr/bucket-name-override

references:
  test_and_build: &test_and_build
    name: Build Docs Site
    command: |
      set -e
      cd ./docs
      npm install
      npm run check-links
      npm run build

jobs:
  test:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run: *test_and_build

workflows:
  version: 2
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
      - oss-docs/publish-docs:
          repository: insights-docs
          bucket-name-override: insights.docs.fairwinds.com
          filters:
            branches:
              only: sudermanjr/bucket-name-override
