references:
  test_and_build: &test_and_build
    name: Build Docs Site
    command: |
      set -e
      cd ./docs
      npm install
      npm run check-links
      npm run build


jobs:
  test:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run: *test_and_build

  publish_docs:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run: *test_and_build
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Publish Docs Site to S3
          command: |
            cd ./dist
            aws s3 sync ./ s3://insights.docs.fairwinds.com --delete

workflows:
  version: 2
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
      - publish_docs:
          filters:
            branches:
              only: main
